pipelines:
  pull-requests:
    '{develop,test,main,feature/*,bugfix/*,hotfix/*,epic/*}':
      import: base-pipelines:main:pull-request-steps

  branches:
    test:
      import: base-pipelines:main:docker-build-push-dev

  tags:
    '*.*.*':
      import: base-pipelines:main:docker-build-push-prod
