version: '3.8'
services:
  php-fpm:
    image: registry.digitalocean.com/coddin/laravel-fpm-base-dev:1.0.0
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    environment:
      - DB_HOST=db
    networks:
      - backend-network
    depends_on:
      db:
        condition: service_healthy
  build:
    image: registry.digitalocean.com/coddin/laravel-build-base-dev:1.0.0
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 5173:5173
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    ports:
      - 8888:80
    networks:
      - backend-network
    depends_on:
      - php-fpm
  db:
    image: mysql:latest
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-network
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
networks:
  backend-network:
    driver: bridge

volumes:
  db-data:
